#  Central Limit Theorem <hr style="border:2.5px solid #126782"></hr>

<b>Jericho A. Rendon</b>
<br>Comptech Student

In [39]:
# imports and packages
import pandas as pd
import numpy as np

In [40]:
# loading dataset
df = pd.read_csv(r'C:\Users\ASUS\OneDrive\Desktop\dataset\water_quality1.csv')

In [41]:
df.head()

     Ph   Turbidity  Temperature  Conductivity  Label
0  7.01  706.101031    20.529632    342.543917      1
1  7.25  721.232354    25.355915    325.120790      1
2  6.88  596.178640    29.599519    365.238751      1
3  7.89  674.121989    11.838675    259.524332      1
4  8.21  505.266735    14.167877    298.184947      1

In [42]:
# storage of means
means_data = {col: [] for col in df.columns}

In [43]:
np.random.seed(3000)

# sampling means
for _ in range(3000): # 3000 times
    for c in df.columns:
        sample = np.random.choice(df[c], size=30, replace=True)
        means_data[c].append(np.mean(pd.to_numeric(sample, errors='coerce')))

In [44]:
df_means = pd.DataFrame(means_data)
df_means

            Ph    Turbidity  Temperature  Conductivity     Label
0     8.504333  1375.221525    22.719184    465.247172  0.433333
1     6.159333   978.532379    23.952153    428.833372  0.433333
2     6.633667  1159.209326    23.368132    442.648445  0.533333
3     7.200333  1054.956594    23.883212    346.962559  0.566667
4     6.991333   896.948143    24.860525    466.599709  0.633333
...        ...          ...          ...           ...       ...
2995  7.426000  1153.299794    21.607775    414.818288  0.366667
2996  7.002000   823.371555    25.151469    413.000303  0.366667
2997  7.436000   849.171470    20.409214    436.248560  0.333333
2998  8.348000  1284.040921    26.598722    471.530904  0.533333
2999  7.892333  1217.254235    23.112261    411.469160  0.500000

[3000 rows x 5 columns]

In [45]:
import os

os.makedirs('raw', exist_ok=True)
df_means.to_csv(r'C:\Users\ASUS\OneDrive\Desktop\dataset\water_pollution_disease_k.csv', index=False)