#  Central Limit Theorem <hr style="border:2.5px solid #126782"></hr>

<b>Gyro A. Madrona</b>
<br>Electronics Engineer

In [63]:
# imports and packages
import pandas as pd
import numpy as np

In [64]:
# loading dataset
df = pd.read_csv(r'raw\electricity-sample-dataset.csv')

In [65]:
df.head()

   Nuclear  Wind  Hydroelectric  Oil and Gas  Coal  Solar  Biomass
0     1381   360           2305         1068  1186      0       42
1      688   337           2816          515   725      0       33
2     1350   411           1185         1045  1856    583       41
3     1405  1461           1998         1578  1109      0       81
4      695   408           3160          573   853     63       48

In [66]:
# storage of means
means_data = {col: [] for col in df.columns}

In [67]:
np.random.seed(42)

# sampling means
for _ in range(50): # 50 times
    for c in df.columns:
        sample = np.random.choice(df[c], size=30, replace=True)
        means_data[c].append(np.mean(sample))

In [68]:
df_means = pd.DataFrame(means_data)
df_means

,Nuclear,Wind,Hydroelectric,Oil and Gas,Coal,Solar,Biomass
0,1338.433333,894.600000,1815.133333,1167.533333,1128.700000,142.400000,52.700000
1,1260.200000,800.033333,1776.900000,1055.766667,1105.233333,215.966667,55.100000
2,1190.666667,876.466667,1854.433333,1190.533333,1276.466667,164.100000,58.233333
3,1182.733333,571.100000,1626.733333,1185.566667,1191.833333,172.500000,53.100000
4,1344.566667,461.233333,1871.933333,1325.466667,1332.466667,140.000000,54.433333
5,1314.700000,844.033333,1600.266667,1203.433333,1282.966667,180.200000,49.600000
6,1264.266667,841.566667,1705.666667,1217.100000,1170.466667,155.433333,53.866667
7,1317.300000,657.300000,1825.433333,1245.633333,1119.200000,205.133333,55.200000
8,1344.600000,942.433333,1637.800000,1124.466667,1174.133333,194.233333,60.366667
9,1274.633333,779.833333,1843.400000,1066.033333,1112.733333,113.800000,55.000000
10,1217.400000,681.133333,1926.400000,1115.500000,1315.000000,262.900000,52.566667
11,1275.966667,843.566667,1780.333333,1180.733333,1182.100000,142.533333,53.633333
12,1323.633333,668.366667,1868.666667,1310.500000,1140.800000,105.100000,55.066667
13,1257.900000,847.366667,2092.933333,1133.400000,1212.433333,152.600000,57.266667
14,1254.900000,946.866667,1931.000000,1008.433333,1184.566667,143.500000,58.166667
15,1191.600000,688.566667,1675.666667,1170.666667,1199.300000,122.233333,49.300000
16,1332.500000,764.366667,1836.133333,1078.466667,1191.433333,223.400000,53.266667
17,1335.666667,725.966667,2017.000000,1212.466667,1067.233333,100.366667,52.400000
18,1258.000000,599.533333,1864.733333,1169.566667,1178.700000,182.233333,57.300000
19,1332.266667,929.900000,1713.233333,1122.666667,1068.433333,137.566667,54.333333
20,1349.133333,1213.766667,1662.466667,1291.766667,1174.900000,265.800000,50.466667
21,1269.166667,1021.366667,1700.066667,1315.433333,1201.233333,195.100000,51.266667
22,1239.966667,766.633333,1528.066667,1262.900000,1104.100000,134.400000,53.400000
23,1237.933333,796.366667,1993.633333,1297.966667,1201.333333,200.566667,55.966667
24,1362.533333,1011.266667,1618.666667,1304.933333,1060.400000,157.300000,56.100000
25,1284.333333,706.766667,1907.733333,1242.100000,1159.733333,178.900000,53.133333
26,1282.566667,910.400000,1778.833333,1088.933333,1042.866667,172.366667,56.566667
27,1289.933333,726.700000,1804.733333,1248.666667,1079.333333,218.466667,55.766667
28,1267.566667,566.766667,1698.000000,1064.033333,1139.000000,106.200000,55.033333
29,1253.266667,657.466667,1907.600000,1235.233333,976.733333,221.366667,53.200000
30,1286.400000,716.200000,1769.766667,1204.633333,1155.700000,169.766667,52.066667
31,1264.000000,563.500000,2003.766667,1221.800000,1246.333333,106.033333,54.166667
32,1280.366667,894.433333,1756.600000,1220.333333,1011.333333,76.933333,55.600000
33,1357.800000,843.833333,1938.133333,1114.266667,1070.100000,195.133333,48.466667
34,1311.233333,727.233333,1926.933333,1107.000000,1111.366667,181.200000,56.033333
35,1359.933333,636.100000,1575.233333,1178.733333,1197.533333,197.566667,56.100000
36,1328.300000,719.100000,1737.700000,1068.800000,1198.133333,144.366667,54.166667
37,1345.000000,750.266667,1498.866667,1001.900000,1232.300000,176.500000,52.000000
38,1294.533333,686.566667,1820.900000,1114.933333,1171.900000,150.500000,53.566667
39,1246.933333,654.833333,1766.566667,1156.066667,1133.500000,187.300000,55.133333
40,1260.233333,810.733333,1501.333333,1181.666667,1182.266667,163.200000,55.966667
41,1257.700000,709.533333,1888.633333,1187.300000,1119.766667,207.600000,56.000000
42,1288.933333,966.433333,1806.966667,1141.833333,1115.533333,170.933333,56.566667
43,1314.300000,718.266667,1816.300000,1004.866667,1156.800000,138.400000,57.666667
44,1221.966667,628.666667,1759.300000,1117.733333,1168.500000,193.000000,57.266667
45,1328.733333,502.500000,1705.466667,1010.133333,1097.266667,202.600000,56.833333
46,1291.333333,719.966667,1664.400000,1159.933333,1163.966667,204.833333,55.466667
47,1252.033333,652.033333,1575.366667,1148.433333,1201.800000,265.766667,55.466667
48,1211.933333,784.366667,2025.833333,1135.366667,1172.933333,226.133333,55.133333
49,1218.700000,749.733333,1906.800000,1220.200000,1111.833333,156.066667,52.633333

In [69]:
df_means.to_csv(r'raw\electricity-clt-dataset-test.csv', index=False)